version: '3.8'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_IP}
    hostname: plexserver.example.com
    volumes:
      - ${DOCKERCONFDIR}/plex:/config
      - ${DOCKERCONFDIR}/plex:/transcode
      - ${DOCKERSTORAGEDIR}:/storage
    restart: ${RESTART}

  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/overseerr:/app/config
      - ${DOCKERSTORAGEDIR}:/storage
    restart: ${RESTART}

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    restart: ${RESTART}
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_CLIENT}
      - OPENVPN_USER=${VPN_USER}
      - OPENVPN_PASSWORD=${VPN_PASS}
      - TZ=${VPN_TZ}
    volumes:
      - /home/raph/gluetun:/gluetun
    ports:
      - 7878:7878/tcp
      - 8989:8989/tcp
      - 6881:6881/tcp
      - 9091:9091/tcp
      - 9696:9696/tcp
      - 51413:51413/tcp
      - 51413:51413/udp

  radarr:
    container_name: radarr
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Chicago
    image: lscr.io/linuxserver/radarr
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    network_mode: "service:gluetun"
    restart: ${RESTART}
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: ${DOCKERCONFDIR}/radarr
      target: /config
      bind:
        create_host_path: true
    - type: bind
      source: ${DOCKERSTORAGEDIR}
      target: /storage
      bind:
        create_host_path: true

  sonarr:
    container_name: sonarr
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Chicago
    image: lscr.io/linuxserver/sonarr:develop
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    network_mode: "service:gluetun"
    restart: ${RESTART}
    volumes:
    - type: bind
      source: /etc/localtime
      target: /etc/localtime
      read_only: true
      bind:
        create_host_path: true
    - type: bind
      source: ${DOCKERCONFDIR}/sonarr
      target: /config
      bind:
        create_host_path: true
    - type: bind
      source: ${DOCKERSTORAGEDIR}
      target: /storage
      bind:
        create_host_path: true

  transmission:
    container_name: transmission
    environment:
      PGID: "1000"
      PUID: "1000"
      TZ: America/Chicago
    image: lscr.io/linuxserver/transmission
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: 200k
    network_mode: "service:gluetun"
    restart: ${RESTART}
    volumes:
    - ${DOCKERCONFDIR}/transmission:/config
    - ${DOCKERSTORAGEDIR}/downloads:/downloads

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERCONFDIR}/portainer:/data
    restart: ${RESTART}

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERCONFDIR}/prowlarr:/config
      - ${DOCKERCONFDIR}/prowlarr:/downloads
    restart: ${RESTART}
